import * as stylex from "@stylexjs/stylex";

export const profileStyles = stylex.create({
  page: { maxWidth: "1200px", marginInline: "auto", paddingBottom: "100px" },
  hero: {
    position: "relative",
    isolation: "isolate",
    overflow: "hidden",
    borderRadius: "10px",
    backgroundColor: "#19241d",
  },
  banner: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    objectPosition: "center 35%",
    zIndex: -2,
  },
  shade: {
    position: "absolute",
    inset: 0,
    zIndex: -1,
    backgroundImage:
      "linear-gradient(180deg, rgb(8 14 10 / 12%), rgb(8 14 10 / 30%) 25%, rgb(8 14 10 / 92%) 100%)",
  },
  heroTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "16px",
    padding: "24px 28px",
  },
  eyebrow: {
    margin: 0,
    color: "#c9d7cc",
    fontSize: "11px",
    fontWeight: 600,
    letterSpacing: "0.16em",
    textTransform: "uppercase",
  },
  identity: {
    display: "flex",
    alignItems: "end",
    gap: "20px",
    padding: { default: "94px 36px 32px", "@media (max-width: 600px)": "64px 24px 24px" },
  },
  avatar: {
    width: "68px",
    height: "68px",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    borderRadius: "50%",
    border: "1px solid #749681",
    backgroundColor: "#243d2e",
    color: "#d7e9dc",
    fontSize: "22px",
    fontWeight: 500,
  },
  name: {
    margin: "8px 0 0",
    fontSize: { default: "40px", "@media (max-width: 600px)": "28px" },
    lineHeight: 1.05,
    letterSpacing: "-0.035em",
    fontWeight: 500,
    overflowWrap: "anywhere",
  },
  content: { paddingInline: { default: "32px", "@media (max-width: 760px)": "16px" } },
  stats: {
    display: "flex",
    flexWrap: "wrap",
    gap: "24px 44px",
    margin: 0,
    paddingBlock: "26px",
    borderBottom: "1px solid #2b3029",
  },
  stat: { display: "grid", gap: "5px" },
  statValue: { margin: 0, fontSize: "24px", fontWeight: 500, fontVariantNumeric: "tabular-nums" },
  muted: { color: "#a5ada2", fontSize: "13px", lineHeight: 1.6, margin: 0 },
  section: { paddingTop: "36px", display: "grid", gap: "20px" },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "12px",
  },
  title: { margin: "0 0 4px", fontSize: "23px", fontWeight: 500, letterSpacing: "-0.025em" },
  link: {
    color: { default: "#bfdec8", ":hover": "#e5f8eb" },
    textDecoration: "none",
    fontSize: "13px",
    borderRadius: "3px",
    outlineOffset: "4px",
    ":focus-visible": { outline: "2px solid #11c565" },
  },
  features: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@media (max-width: 600px)": "repeat(2, minmax(0, 1fr))",
    },
    gap: { default: "24px", "@media (max-width: 760px)": "14px" },
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  slot: { minWidth: 0, display: "flex", flexDirection: "column", gap: "10px" },
  emptySlot: {
    width: "100%",
    height: "auto",
    aspectRatio: "5 / 7",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    borderWidth: "1px",
    borderStyle: "dashed",
    borderColor: "#45503f",
    backgroundColor: "#141811",
    borderRadius: "10px",
    color: "#afbfa4",
    whiteSpace: "normal",
  },
  slotNumber: { fontSize: "32px", fontWeight: 300, color: "#687760" },
  cardName: {
    margin: 0,
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: 1.4,
    overflowWrap: "anywhere",
  },
  slotFooter: { display: "flex", justifyContent: "space-between", alignItems: "start", gap: "4px" },
  actions: { display: "flex", gap: "6px", flexWrap: "wrap", alignItems: "center" },
  collection: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(6, minmax(0, 1fr))",
      "@media (max-width: 760px)": "repeat(3, minmax(0, 1fr))",
    },
    gap: "16px",
    listStyle: "none",
    padding: 0,
    margin: 0,
  },
  empty: {
    padding: "28px",
    border: "1px solid #30372b",
    borderRadius: "10px",
    display: "grid",
    justifyItems: "start",
    gap: "12px",
  },
  error: { margin: 0, color: "#ffb8a8", fontSize: "13px" },
  dialog: {
    width: "min(780px, calc(100vw - 40px))",
    maxHeight: "85vh",
    overflowY: "auto",
    display: "grid",
    gap: "18px",
  },
  search: { display: "flex", alignItems: "end", gap: "12px" },
  field: { flex: 1, minWidth: 0, display: "grid", gap: "8px", fontSize: "13px" },
  pickerGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@media (max-width: 600px)": "repeat(2, minmax(0, 1fr))",
    },
    gap: "14px",
    padding: 0,
    margin: 0,
    listStyle: "none",
  },
  pick: {
    width: "100%",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    padding: "8px",
    gap: "8px",
    whiteSpace: "normal",
    textAlign: "left",
  },
});
