packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  "@base-ui/react": ^1.6.0
  "@better-auth/electron": 1.6.25
  "@cloudflare/vitest-pool-workers": 0.20.1
  "@oxlint/plugins": 1.78.0
  "@stylexjs/stylex": ^0.19.0
  "@stylexjs/unplugin": ^0.19.0
  "@tanstack/react-query": ^5.101.4
  "@tanstack/react-router": ^1.170.18
  "@tanstack/router-plugin": ^1.168.23
  "@types/node": ^22.20.1
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.4
  better-auth: 1.6.25
  electron: ^43.2.0
  electron-builder: 26.15.3
  hono: ^4.12.32
  mana-font: ^1.18.0
  motion: ^12.42.2
  oxlint: 1.78.0
  react: ^19.2.8
  react-dom: ^19.2.8
  typescript: ^7.0.2
  unplugin: 2.3.11
  uuid: 14.0.1
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plugin-electron: ^1.1.0
  vite-plus: 0.2.6
  vitest: 4.1.10
  wrangler: ^4.113.0
  zod: ^4.4.3
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  electron-winstaller: false
  esbuild: true
  sharp: false
  workerd: true
