/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CollectionRouteImport } from "./routes/collection";
import { Route as DecksRouteImport } from "./routes/decks";
import { Route as ListsRouteImport } from "./routes/lists";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as SetsRouteImport } from "./routes/sets";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as CardsPrintingIdRouteImport } from "./routes/cards.$printingId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const CollectionRoute = CollectionRouteImport.update({
  id: "/collection",
  path: "/collection",
  getParentRoute: () => rootRouteImport,
} as any);
const DecksRoute = DecksRouteImport.update({
  id: "/decks",
  path: "/decks",
  getParentRoute: () => rootRouteImport,
} as any);
const ListsRoute = ListsRouteImport.update({
  id: "/lists",
  path: "/lists",
  getParentRoute: () => rootRouteImport,
} as any);
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const SetsRoute = SetsRouteImport.update({
  id: "/sets",
  path: "/sets",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const CardsPrintingIdRoute = CardsPrintingIdRouteImport.update({
  id: "/cards/$printingId",
  path: "/cards/$printingId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/collection": typeof CollectionRoute;
  "/decks": typeof DecksRoute;
  "/lists": typeof ListsRoute;
  "/search": typeof SearchRoute;
  "/sets": typeof SetsRoute;
  "/settings": typeof SettingsRoute;
  "/cards/$printingId": typeof CardsPrintingIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/collection": typeof CollectionRoute;
  "/decks": typeof DecksRoute;
  "/lists": typeof ListsRoute;
  "/search": typeof SearchRoute;
  "/sets": typeof SetsRoute;
  "/settings": typeof SettingsRoute;
  "/cards/$printingId": typeof CardsPrintingIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/collection": typeof CollectionRoute;
  "/decks": typeof DecksRoute;
  "/lists": typeof ListsRoute;
  "/search": typeof SearchRoute;
  "/sets": typeof SetsRoute;
  "/settings": typeof SettingsRoute;
  "/cards/$printingId": typeof CardsPrintingIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/collection"
    | "/decks"
    | "/lists"
    | "/search"
    | "/sets"
    | "/settings"
    | "/cards/$printingId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/collection"
    | "/decks"
    | "/lists"
    | "/search"
    | "/sets"
    | "/settings"
    | "/cards/$printingId";
  id:
    | "__root__"
    | "/"
    | "/collection"
    | "/decks"
    | "/lists"
    | "/search"
    | "/sets"
    | "/settings"
    | "/cards/$printingId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CollectionRoute: typeof CollectionRoute;
  DecksRoute: typeof DecksRoute;
  ListsRoute: typeof ListsRoute;
  SearchRoute: typeof SearchRoute;
  SetsRoute: typeof SetsRoute;
  SettingsRoute: typeof SettingsRoute;
  CardsPrintingIdRoute: typeof CardsPrintingIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/collection": {
      id: "/collection";
      path: "/collection";
      fullPath: "/collection";
      preLoaderRoute: typeof CollectionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/decks": {
      id: "/decks";
      path: "/decks";
      fullPath: "/decks";
      preLoaderRoute: typeof DecksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/lists": {
      id: "/lists";
      path: "/lists";
      fullPath: "/lists";
      preLoaderRoute: typeof ListsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sets": {
      id: "/sets";
      path: "/sets";
      fullPath: "/sets";
      preLoaderRoute: typeof SetsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cards/$printingId": {
      id: "/cards/$printingId";
      path: "/cards/$printingId";
      fullPath: "/cards/$printingId";
      preLoaderRoute: typeof CardsPrintingIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  DecksRoute: DecksRoute,
  ListsRoute: ListsRoute,
  SearchRoute: SearchRoute,
  SetsRoute: SetsRoute,
  SettingsRoute: SettingsRoute,
  CardsPrintingIdRoute: CardsPrintingIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
